export const NODE_TYPES = {
  SOURCE: 0,
  DESTINATION: 1,
  AUDIONODE: 2
};

export const MODAL_TYPES = {
  ADD_INPUT: "ADD_INPUT",
  ADD_OUTPUT: "ADD_OUTPUT",
  ADD_CONNECTION: "ADD_CONNECTION",
  EDIT_GAIN: "EDIT_GAIN",
};