export const NODE_TYPES = {
  SOURCE: "SOURCE",
  DESTINATION: "DESTINATION",
  AUDIONODE: "AUDIONODE"
};

export const MODAL_TYPES = {
  ADD_INPUT: "ADD_INPUT",
  ADD_OUTPUT: "ADD_OUTPUT",
  ADD_CONNECTION: "ADD_CONNECTION",
  ADD_AUDIO_NODE: "ADD_AUDIO_NODE",
  EDIT_AUDIO_NODE: "EDIT_AUDIO_NODE",
  NODE_CONTEXT_MENU: "NODE_CONTEXT_MENU",
  CONNECTION_CONTEXT_MENU: "CONNECTION_CONTEXT_MENU",
};
